### ISSUE TITLE
Operations don't work when React Native Debugger / devtools is open

### ISSUE THREAD

**Issue by hellogerard** [VirgilSecurity/react-native-virgil-crypto#4]
Hello, I have been experimenting with this package and it is working well!  However, it's hard to log anything because whenever I try to encrypt/decrypt anything with devtools open ([Chrome](https://facebook.github.io/react-native/docs/debugging#chrome-developer-tools) or the [React Native Debugger](https://github.com/jhen0409/react-native-debugger)), I get this error.

<img width="400" src="https://user-images.githubusercontent.com/200488/64288306-c6f70200-cf2f-11e9-9206-aff9b5f4b40a.png">

[Digging deeper](https://medium.com/@some_day_man/synchronous-returns-in-react-native-native-modules-453af33d5999), looks like this is "expected" when calling synchronous functions in native modules.

Sorry, I'm not a native developer, so any particular reason these calls are not asynchronous?  Any ideas on getting the devtools to work with this package? It's hard to develop an end-to-end-encrypted app w/o proper logging/debugging.

**Comment by vadimavdeev** [comment]
Hello, those methods are indeed not supported under the websocket executor (Chrome Debugger) unfortunately. The reason those methods are synchronous is for this library to be API-compatible with the javascript virgil-crypto so that you can swap this library in for use in E3kit, for example.

You can still log anything you want in JS with a simple `console.log()`. Just make sure your IDE does _not_ add an `import console = require('console');` to your module imports. You can see these logs in Android Studio or XCode, or even [in terminal](https://facebook.github.io/react-native/docs/debugging#accessing-console-logs). And you can debug the [native code](https://facebook.github.io/react-native/docs/debugging#debugging-native-code) in Android Studio or XCode just like a standard native app.

**Comment by hellogerard** [comment]
Got it. The debugger gives us other tools like Redux devtools and Apollo devtools, but we can work thru this. I will close.
